### PR TITLE
Refactored tests, removed testify/assert

### LINKED ISSUE #2: Improve tests
We should improve the tests to:
- be more Go-like and use only stuff available within the standard Go library
- remove the dependency to stretchr/assert: it's a lovely library, but for a project this size, we can avoid using it

### PR DESCRIPTION
**Pull request by RomanSerikov**
Hi!

I tried to resolve #2. 

Hope you like it :)

### CODE REVIEW

**Review by LukaszKokot — APPROVED** [review]
Nice ! Looks good to me :rocket:

**Review by LukaszKokot — COMMENTED** [review]
Wait, forgot just one thing! Could you please run `go mod tidy` ? Since we don't use the `assert` package, it can now be safely removed :slightly_smiling_face:

**Comment by RomanSerikov** [comment]
You are right, forgot about it :)

**Review by jmaitrehenry — APPROVED** [review]
LGTM

**Pull request merged**
